#!/bin/bash

sandboxdir="$(dirname $0)/.snakes"
if [ ! -d "$sandboxdir" ]; then
	sandbox "$sandboxdir" -g bundler
	source "$sandboxdir/bin/activate_sandbox"
	bundle install
	deactivate_sandbox
fi
source "$sandboxdir/bin/activate_sandbox"
rake test
deactivate_sandbox
